In [73]:
import numpy as np
dictionary = {"Joe": np.array([1,2,3]), "Joe" : np.array([4,5,6])}

In [74]:
{"a": np.array([1,2,3]), "a": np.array([2,4,5]) }

{'a': array([2, 4, 5])}

In [75]:
len(dictionary["Joe"])

3

In [76]:
dictionary["Joe"] = [dictionary["Joe"], np.array([1,2,3])]

In [77]:
dictionary["Joe"]

[array([4, 5, 6]), array([1, 2, 3])]

In [78]:
dictionary["Joe"] = [np.array([1, 2, 3])]

In [79]:
np.array(dictionary["Joe"]).mean(axis = 0)

array([ 1.,  2.,  3.])

In [80]:
dictionary["Bob"] = [np.array([1, 2, 3]), np.array([4,6,2])]

In [81]:
dictionary["Jerry"] = [np.array([1, 2, 3]), np.array([34,23,54])]

In [91]:
for key in dictionary:
    dictionary[key] = np.array(dictionary[key]).mean(axis = 0)

In [92]:
dictionary

{'Bob': 3.0, 'Jerry': 19.5, 'Joe': 2.0}

In [89]:
def L2_dists(x, y):
    """ Computing L2 distances using memory-efficient
        vectorization.

        Parameters
        ----------
        x : numpy.ndarray, shape=(D,)
        y : numpy.ndarray, shape=(D,)

        Returns
        -------
        numpy.ndarray, shape=(D,)
            The Euclidean distance between each pair of
            rows between `x` and `y`."""
    dists = -2 * np.matmul(x, y.T)
    dists +=  np.sum(x**2)[np.newaxis]
    dists += np.sum(y**2)
    return  np.sqrt(dists)

In [90]:
pairwise_dists(np.array([1,2,3]), np.array([4,5,6]))

array([ 5.19615242])

In [119]:
dictionary = {'Bob': 300000, 'Jerry': 4000000, 'Joe': 200.0, 'Ralph': 0}


In [120]:
from collections import OrderedDict 

In [127]:
OrderedDict(invert_dictionary(dictionary))
sorted(list(invert_dictionary(dictionary).keys()))

[0, 200.0, 300000, 4000000]

In [130]:
list = [i for i in range(10)]

In [134]:
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [137]:
aray = np.array(list
        )

In [138]:
aray = aray[aray < 6]

In [139]:
aray

array([0, 1, 2, 3, 4, 5])

In [141]:
type("a") == str

True